# Generated by Django 5.1.6 on 2025-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_groups_remove_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="", max_length=64, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=64, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=16, unique=True, verbose_name="Phone number"
            ),
        ),
    ]
