version: "3.9"

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    container_name: finka_back
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: finka_db
    restart: always
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5436:5432"

volumes:
  postgres_data: