# Generated by Django 5.1.6 on 2025-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Дата совершения транзакции")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма транзакции в рублях",
                        max_digits=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Категория транзакции (например, 'Продукты', 'Развлечения')",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
